### ISSUE TITLE
Downloadable jar

### ISSUE THREAD

**Issue by caspertone2003** [ThomasDaheim/GPXEditor#45]
HI,
Could you release a jar file so testing your sw does not require building the jar?
TIA,
CT

**Comment by ThomasDaheim** [comment]
On my todo list since some time :-) I planned putting it into any known repository but that is some effort. Maybe I should go for adding a jar right here in the repo...

**Comment by caspertone2003** [comment]
Thanks for answering!
Yes, uploading as a release should be the lest effort...
CT

**Comment by ThomasDaheim** [comment]
I have simply added my current versions of GPXEditor and JavaHelper. The rest are all dependencies that are available through maven...

**Comment by caspertone2003** [comment]
Thanks!
Downloaded, will try in next days
